name: Image Build Check

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
    paths:
      - 'ci.Dockerfile'
      - 'dev.Dockerfile'
      - 'scripts/wasm-deps.sh'
      - '.github/workflows/image-development.yaml'

jobs:
  check-images:
    name: Validate Image Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ['ci.Dockerfile', 'dev.Dockerfile']
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: Build image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          file: ./${{ matrix.file }}
          push: false
