name: Security Analysis

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
  schedule:
    - cron: '23 3 * * *' # Daily at 03:23 UTC

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript-typescript', 'rust']

    steps:
      - name: Run actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run github/codeql-action/init
        uses: github/codeql-action/init@c10b8064de6f491fea524254123dbe5e09572f13 # v4
        with:
          languages: ${{ matrix.language }}
      - name: Run actions/cache
        if: matrix.language == 'rust'
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src/wasudoku-wasm/target/
          key: ${{ matrix.language }}-${{ runner.os }}-cargo-${{ hashFiles('src/wasudoku-wasm/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.language }}-${{ runner.os }}-cargo-
      - name: Run dtolnay/rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'wasm32-unknown-unknown'
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run actions/setup-node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install UI dependencies
        run: npm ci
      - name: Build project for analysis
        run: |
          npm run wasm:build:prod
          npm run typecheck
      - name: Run github/codeql-action/analyze
        uses: github/codeql-action/analyze@c10b8064de6f491fea524254123dbe5e09572f13 # v4
        with:
          category: '/language:${{matrix.language}}'
